# Define o nome do seu workflow
name: Checagem de IP Público

# O evento que dispara o workflow.
# A express\u00E3o cron '0 0 * * *' significa "executar uma vez por dia, \u00E0 meia-noite (UTC)".
# O evento 'workflow_dispatch' permite a execu\u00E7\u00E3o manual.
on:
  schedule:
    - cron: '0 0 * * *'
  # Adicione esta linha para permitir a execu\u00E7\u00E3o manual a partir da interface do GitHub
  workflow_dispatch:

# Os "trabalhos" (jobs) que ser\u00E3o executados pelo workflow
jobs:
  build:
    # O tipo de sistema operacional que ser\u00E1 usado para o trabalho
    runs-on: ubuntu-latest

    # Os passos do trabalho
    steps:
      # Pega o c\u00F3digo do seu reposit\u00F3rio
      - name: Checkout do c\u00F3digo
        uses: actions/checkout@v4

      # Configura o ambiente Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a vers\u00E3o mais recente do Python 3

      # Instala as depend\u00EAncias do seu script (a biblioteca requests)
      - name: Instalar depend\u00EAncias
        run: pip install requests

      # Executa seu script Python usando o caminho completo a partir da raiz do reposit\u00F3rio
      # O nome da pasta "meu ip" foi corrigido e colocado entre aspas para evitar problemas com o espa\u00E7o.
      - name: Executar bot de IP
        run: python "meu ip"/ip.py
