# Define o nome do seu workflow
name: Checagem de IP Público

# O evento que dispara o workflow.
# A expressão cron '*/10 * * * *' significa "executar a cada 10 minutos".
# O evento 'workflow_dispatch' permite a execução manual.
on:
  schedule:
    - cron: '*/10 * * * *'
  # Adicione esta linha para permitir a execução manual a partir da interface do GitHub
  workflow_dispatch:

# Os "trabalhos" (jobs) que serão executados pelo workflow
jobs:
  build:
    # O tipo de sistema operacional que será usado para o trabalho
    runs-on: ubuntu-latest

    # Os passos do trabalho
    steps:
      # Pega o código do seu repositório
      - name: Checkout do c\u00F3digo
        uses: actions/checkout@v4

      # Configura o ambiente Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a vers\u00E3o mais recente do Python 3

      # Instala as depend\u00EAncias do seu script (a biblioteca requests)
      - name: Instalar depend\u00EAncias
        run: pip install requests

      # Executa seu script Python
      # O caminho do arquivo foi corrigido para a raiz do reposit\u00F3rio
      - name: Executar bot de IP
        run: python ip_getter.py
