# Define o nome do seu workflow
name: Bot da Twitch

# O evento que dispara o workflow.
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# Os "trabalhos" (jobs) que ser\u00E3o executados pelo workflow
jobs:
  build:
    # O tipo de sistema operacional que ser\u00E1 usado para o trabalho
    runs-on: ubuntu-latest

    # Os passos do trabalho
    steps:
      # Pega o c\u00F3digo do seu reposit\u00F3rio
      - name: Checkout do c\u00F3digo
        uses: actions/checkout@v4
      
      # Instala o Google Chrome e o driver correspondente, o que \u00E9 necess\u00E1rio para o Selenium
      - name: Configurar Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          # Vers\u00E3o est\u00E1vel do Chrome
          chrome-version: 'stable'

      # Configura o ambiente Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Instala as depend\u00EAncias do seu script (Selenium e undetected_chromedriver)
      - name: Instalar depend\u00EAncias
        run: pip install selenium undetected-chromedriver

      # Executa seu script Python usando o caminho completo a partir da raiz do reposit\u00F3rio
      - name: Executar bot da Twitch
        run: python "meu ip"/"meu ip".py
